Documentation for Meal Voucher Issuer endpoints
mollie/api-documentation pull request #645
Opened 2020-08-07 07:27 UTC by actuallymab

2020-08-07 15:01 UTC, mattijsbliek commented on source/reference/v2/profiles-api/enable-meal-voucher-issuer.rst
> +           --data-raw '{ "contractId": "foo" }'
Let's make this `abc123` instead of `foo` to make it more "ID-like"

2020-08-07 15:03 UTC, mattijsbliek commented on source/reference/v2/profiles-api/enable-meal-voucher-issuer.rst
> +the issuer's ID you want to activate, for example ``appetiz``.
```suggestion
the issuer you want to activate, for example ``appetiz``.
```

2020-08-07 15:03 UTC, mattijsbliek commented on source/reference/v2/profiles-api/enable-meal-voucher-issuer.rst
> +Replace ``id`` in the endpoint URL by the profile's ID, for example ``pfl_v9hTwCvYqw`` and ``issuer`` with the name of
```suggestion
Replace ``id`` in the endpoint URL by the profile's ID, for example ``pfl_v9hTwCvYqw`` and ``issuer`` with the identifier of
```

2020-08-07 15:05 UTC, mattijsbliek commented on source/reference/v2/profiles-api/disable-meal-voucher-issuer.rst
> +the issuer's ID you want to disable, for example ``appetiz``.
See my comment below

2020-08-07 15:06 UTC, mattijsbliek commented on source/reference/v2/profiles-api/enable-meal-voucher-issuer.rst
> +      - The status that the issuer is in. Possible values: ``pending-issuer`` or ``activated``.
This can be `pending-boarding` as well right?

2020-08-07 15:11 UTC, actuallymab commented on source/reference/v2/profiles-api/enable-meal-voucher-issuer.rst
> +      - The status that the issuer is in. Possible values: ``pending-issuer`` or ``activated``.
`pending-boarding` is a status for the payment method which is in this case meal voucher, not for the issuer, right?

2020-08-07 15:28 UTC, mattijsbliek commented on source/reference/v2/profiles-api/enable-meal-voucher-issuer.rst
> +      - The status that the issuer is in. Possible values: ``pending-issuer`` or ``activated``.
But what will the issuer return when I try to active it without going through any of the onboarding? Because it's neither activated nor is it waiting on the issuer. 

I noticed I didn't catch this for the giftcard endpoint either btw. Just tested what happens there, and we give back `pending-issuer`. But even if the issuer activates the method, we won't activate it on our side.

This will be confusing. It's not the fault of the docs PR though, so consider it non-blocking. We might have to take an issue into the current or next sprint to get this resolved.

2020-08-07 19:44 UTC, actuallymab commented on source/reference/v2/profiles-api/enable-meal-voucher-issuer.rst
> +      - The status that the issuer is in. Possible values: ``pending-issuer`` or ``activated``.
I have another issue on my plate also related to listing meal voucher and gift card issuers which is something we can discuss together with this one for the next sprint 👍

2020-08-14 12:49 UTC, MollieRick commented
Please name `mealvouchers` to `vouchers`, also in the URLs. We have changed this :)

2020-08-19 17:27 UTC, mattijsbliek commented
LGTM! 👍

2020-08-19 17:28 UTC, mattijsbliek approved these changes

2020-08-20 08:17 UTC, MollieRick requested changes

2020-08-20 08:17 UTC, MollieRick commented on source/reference/v2/profiles-api/enable-voucher-issuer.rst
> +                "href": "https://api.mollie.com/v2/issuers/cadeaupass",
This seems an error :)

2020-08-20 08:24 UTC, actuallymab commented on source/reference/v2/profiles-api/enable-voucher-issuer.rst
> +                "href": "https://api.mollie.com/v2/issuers/cadeaupass",
🔪

2020-08-20 09:30 UTC, MollieRick approved these changes

2020-10-02 08:34 UTC, merged