PZ-3913 - Adding info about remainder payment details in guides
mollie/api-documentation pull request #671
Opened 2020-09-28 10:44 UTC by MollieRick

2020-09-29 11:23 UTC, willemstuursma commented on source/orders/integrating-vouchers.rst
> +Be aware that the ``remainderDetails`` is only available when the payment was not fully paid with a
"...when the payment was partially paid with a gift card and then the remainder was paid with a different payment method."

2020-09-29 11:25 UTC, willemstuursma commented on source/guides/gift-cards.rst
> +remainder payment when the consumer partially paid with a gift card. Receiving these details is possible
...consumer pays with both a gift card and another payment method.

2020-09-29 12:45 UTC, ndijkstra commented on source/guides/gift-cards.rst
> +gift card.
```suggestion
Be aware that the ``remainderDetails`` is only available when the payment is partially paid with a gift card.
```

2020-10-02 09:54 UTC, pabloroman commented on source/guides/gift-cards.rst
> +a gift card and then the remainder was paid with a different payment method.
What happens if you use `reminderDetails` in a non partially paid payment? Do get an empty object, or no object at all?

2020-10-02 09:55 UTC, pabloroman commented on source/guides/gift-cards.rst
> +Be aware that the ``remainderDetails`` is only available when the payment ws partially paid with
Typo: "the payment **ws** partially paid"

2020-10-02 09:56 UTC, pabloroman commented on source/orders/integrating-vouchers.rst
> +For example: ``GET https://api.mollie.com/v2/payments/tr_xxx?include=details.remainderDetails``. For
Not in the scope of this PR but it makes me a bit sad that the format to include the remainderDetails is different for orders and payments :(

2020-10-02 10:00 UTC, pabloroman commented on source/orders/integrating-vouchers.rst
> +in both the :doc:`Payments API </reference/v2/payments-api/get-payment>` and
Vouchers can't be used in combination with the Payments API, so I think we should remove it here for clarity

2020-10-02 10:04 UTC, pabloroman requested changes

2020-10-02 10:04 UTC, pabloroman commented on source/orders/integrating-vouchers.rst
> +Getting the details of the remainder payment
I would like to rephrase this entire block to something to make it a bit more concise. May I suggest the following:

"You can request additional details (link to https://docs.mollie.com/reference/v2/payments-api/get-payment#payment-method-specific-details) of the multiple payments used to pay a Voucher order using the ``payments.details.remainderDetails`` embed in the Orders API. 

For example ``GET https://api.mollie.com/v2/orders/ord_xxx?embed=payments.details.remainderDetails``

Be aware that the ``remainderDetails`` is only available when the payment was partially paid with
a voucher and then the remainder was paid with a different payment method.

2020-10-02 13:03 UTC, MollieRick commented on source/guides/gift-cards.rst
> +a gift card and then the remainder was paid with a different payment method.
No object at all

2020-10-02 13:04 UTC, MollieRick commented on source/orders/integrating-vouchers.rst
> +For example: ``GET https://api.mollie.com/v2/payments/tr_xxx?include=details.remainderDetails``. For
The one is an include, the order an embed. Thats the biggest (logical) difference

2020-10-02 13:05 UTC, MollieRick commented on source/orders/integrating-vouchers.rst
> +in both the :doc:`Payments API </reference/v2/payments-api/get-payment>` and
You can not create a voucher payment with the Payments API, but you **can** get the details of the payment from it.

2020-10-02 13:10 UTC, MollieRick commented on source/orders/integrating-vouchers.rst
> +Getting the details of the remainder payment
Like said before, it is also possible in the Payments API. I think its good to keep the docs as complete as possible.

2020-10-05 11:26 UTC, pabloroman approved these changes

2020-10-05 11:38 UTC, merged