Updated the use of the javascript example.
mollie/api-documentation pull request #711
Opened 2020-12-13 16:16 UTC by galstyangroup

This ID should not be passed in the body but as an additional parameter. Also added metadata example.

2020-12-30 19:23 UTC, vernondegoede requested changes

2020-12-30 19:23 UTC, vernondegoede commented on source/reference/v2/customers-api/update-customer.rst
> +        const customer = await mollieClient.customers.update('cst_8wmqcHMN4U(customerID)' , {
```suggestion
        const customer = await mollieClient.customers.update('cst_8wmqcHMN4U' , {
```

2021-01-05 08:57 UTC, mollierobbert commented
Nice catch Harut.

Showing how to update the `metadata` is a nice suggestion as well, but I left it out for now since it would make the JS snippet inconsistent with the other examples.

I'll merge the PR. Thanks!

2021-01-05 08:57 UTC, vernondegoede approved these changes

2021-01-05 08:57 UTC, merged