Merge 'Hosted Onboarding' in to Mollie Connect documentation
mollie/api-documentation pull request #726
Opened 2021-01-25 13:01 UTC by actuallymab

Updated @arnetm 's [PR](https://github.com/mollie/api-documentation/pull/708).

2021-01-25 17:41 UTC, mattijsbliek requested changes

2021-01-25 17:41 UTC, mattijsbliek commented on source/oauth/onboarding.rst
> +That page will display the Client ID and secret needed for the steps below.
```suggestion
After submitting, you will receive the Client ID and secret needed for the steps below.
```

2021-01-25 17:41 UTC, mattijsbliek commented on source/oauth/onboarding.rst
> +Mollie account your customer creates or logs into. This :doc:`page </oauth/overview>` gives you an overview of the flow. If you just want to follow the implementation steps, follow this guide: :doc:`
```suggestion
Mollie organization your customer creates or logs in to. This :doc:`page </oauth/overview>` gives you an overview of the flow. If you just want to follow the implementation steps, follow this guide: :doc:`Mollie Connect getting started </oauth/getting-started>`.
```

2021-01-25 17:41 UTC, mattijsbliek commented on source/oauth/onboarding.rst
> +  .. note::  Make sure to use the Client Id and secret provided of the Hosted Onboarding APP if you want to use this feature. These can be found in the `hosted onboarding settings <https://www.mollie
```suggestion
  .. note::  Make sure to use the Client ID and secret displayed in the `hosted onboarding settings <https://www.mollie.com/dashboard/settings/hosted-onboarding>`_ if you want to make use of this feature.
```

2021-01-25 17:41 UTC, mattijsbliek commented on source/oauth/onboarding.rst
> +Step 2: Customer signs up / logs in and gives authorization
```suggestion
Step 2: Merchant signs up or logs in, and authorizes access to their organization
```

2021-01-25 17:41 UTC, mattijsbliek commented on source/oauth/onboarding.rst
> +Step 2: Customer signs up / logs in and gives authorization
@arnetm We usually try to avoid the term "Customer", since it creates confusion with the Customers API. I do see the existing OAuth Onboarding page already uses this term. What are your thoughts on this?

2021-01-25 17:41 UTC, mattijsbliek commented on source/oauth/onboarding.rst
> +There's two milestones that the customer reaches during the Mollie onboarding, ``canReceivePayments`` (basic information has been provided) and ``canReceiveSettlements`` (all information has been pro
```suggestion
There's two milestones that the customer reaches during the Mollie onboarding, ``canReceivePayments`` and ``canReceiveSettlements``.
```

You won't always receive `canReceivePayments: true` after providing basic information. The consumer should make no assumptions about this.

2021-01-26 10:02 UTC, actuallymab commented on source/oauth/onboarding.rst
> +There's two milestones that the customer reaches during the Mollie onboarding, ``canReceivePayments`` (basic information has been provided) and ``canReceiveSettlements`` (all information has been pro
good one 👍

2021-01-26 10:03 UTC, actuallymab commented on source/oauth/onboarding.rst
> +Step 2: Customer signs up / logs in and gives authorization
I would go with this change.

2021-01-26 10:04 UTC, actuallymab commented
I addressed your suggestions @mattijsbliek thank you! @arnetm maybe you might want to take a final look as well?

2021-01-26 11:42 UTC, mattijsbliek approved these changes
Besides the customer/merchant naming thing there's nothing else from my side. Since the term "customer" is already used in the existing documentation, I don't consider it blocking for this PR.

2021-02-08 10:47 UTC, merged