PZ-4166 Add PayPal Express Checkout Button guide
mollie/api-documentation pull request #733
Opened 2021-02-11 11:34 UTC by MollieRick

2021-02-11 11:49 UTC, ndijkstra requested changes

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +The PayPal Express Checkout button gives your consumers another way to pay, and it complements your
"your customers", "consumers" or "shoppers". Not "your consumers"

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +billing and shipping addresses. This allows you to place the button on any page in your webshop, like
```suggestion
billing and shipping address. This allows you to place the button on any page in your webshop, like
```

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +pack. This button is familiar for the consumer and improves the conversion. Of course its also possible
```suggestion
pack. This button is familiar for the consumer and improves the conversion. Of course it's also possible
```

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +Integration steps for the Orders API
I would leave out "for the Orders API" since it is now looking that there are more possibilities to integrate

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +Using the button with the Orders API is simple, you can use your existing integration with only
I would start with the sentence that it's possible to use it via the Orders API

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +#. Your website :doc:`creates an order </reference/v2/orders-api/create-order>` via the Orders API.
```suggestion
#. Your website :doc:`creates an order </reference/v2/orders-api/create-order>` via the Orders API after the shopper clicks the button.
```

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +   Make sure you set the method to ``paypal`` so that the ``billingAdress`` field is not required.
```suggestion
   Make sure you set the method to ``paypal`` so that the ``billingAddress`` field will not be required anymore.
```

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +                method, or not method at all, your request will result in an HTTP status code
```suggestion
                method, or no method at all, your request will result in a HTTP status code
```

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +#. Redirect your consumer to the ``checkout`` URL which you can find in the response of the Create Order
```suggestion
#. Redirect the shopper to the ``checkout`` URL which you can find in the response of the Create Order
```

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +   API. He or she will select the address where the product(s) needs to be send to and completes the
Wouldn't use "he or she" now these days.

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +   back to your website while we call your webhook to inform you about the latest order state.
Only if they supplied a `webhookUrl`

2021-02-11 11:49 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +#. You can get the shipping address by calling the :doc:`Get order API </reference/v2/orders-api/get-order>`
```suggestion
#. You can retrieve the shipping address by calling the :doc:`Get order API </reference/v2/orders-api/get-order>`
```

2021-02-11 11:49 UTC, ndijkstra commented on source/reference/v2/orders-api/create-order.rst
> +                 Express Checkout button. Make sure you set the ``method`` to ``paypal``.
```suggestion
                 Express Checkout button. Make sure you set ``method`` to ``paypal``.
```

2021-02-11 11:49 UTC, ndijkstra commented on source/reference/v2/orders-api/create-order.rst
> +       .. note:: Even when this field is required, you can leave this out if you are using the PayPal
Just mention that this field is not required when using the PayPal Express Checkout button.

Also link it to the new PayPal button page in the docs.

2021-02-11 11:51 UTC, MollieRick commented on source/orders/paypal-express-checkout-button.rst
> +Integration steps for the Orders API
Good one

2021-02-11 12:01 UTC, ndijkstra commented on package-lock.json
> +          "resolved": "http://registry.npmjs.org/util/-/util-0.10.3.tgz",
Why is this changed?

2021-02-11 12:05 UTC, ndijkstra commented on source/orders/paypal-express-checkout-button.rst
> +                method, or no method at all, your request will result in an HTTP status code
```suggestion
                method, or no method at all, your request will result in a HTTP status code
```

2021-02-12 09:52 UTC, ndijkstra approved these changes

2021-02-12 10:02 UTC, merged

2021-02-12 15:18 UTC, willemstuursma commented
This looks like a nice implementation, go guys!