BL-259 Add expiresAt datetime to payment link api
mollie/api-documentation pull request #747
Opened 2021-04-07 08:24 UTC by Shivella

2021-04-09 12:44 UTC, jeroenvandergeer requested changes

2021-04-09 12:44 UTC, jeroenvandergeer commented on source/reference/v2/payment-links-api/create-payment-link.rst
> +       It will be stored as UTC timezone and customers are able to use the payment link until midnight.
This last sentence is false, if I'm not mistaken Plink will support the time part as well, which means it will be valid until whatever time you set it as.

2021-04-09 12:44 UTC, jeroenvandergeer commented on source/reference/v2/payment-links-api/create-payment-link.rst
> +     - The expire date of the payment link in ISO 8601 format. For example: 2021-12-24T12:00:16+01:00.
Expire date should be `expiry` date

2021-04-09 12:44 UTC, jeroenvandergeer commented on source/reference/v2/payment-links-api/get-payment-link.rst
> +     - The expire date and time the payment link, in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
Same as above `expiry`

2021-04-09 13:10 UTC, Shivella commented on source/reference/v2/payment-links-api/create-payment-link.rst
> +       It will be stored as UTC timezone and customers are able to use the payment link until midnight.
Plink does not support time right now, but sets it to `23:59:59`.
That's why it also returns in the response like that.

2021-04-20 12:19 UTC, jeroenvandergeer requested changes

2021-04-20 12:19 UTC, jeroenvandergeer commented on source/reference/v2/payment-links-api/create-payment-link.rst
> +     - The expiry date of the payment link in ISO 8601 format. For example: 2021-12-24T12:00:16+01:00. It will always stored as UTC timezone.
Change `It will always stored as UTC timezone.` to `It will always be stored in UTC timezone.`

2021-04-20 12:19 UTC, jeroenvandergeer commented on source/reference/v2/payment-links-api/get-payment-link.rst
> +     - The expiry date and time the payment link, in `ISO 8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
Missing the word `of` here (the expiry date and time **of** the payment link)

2021-04-20 17:19 UTC, jeroenvandergeer approved these changes

2021-04-21 07:40 UTC, merged