PZ-4639 Improve PayPal info for description param
mollie/api-documentation pull request #805
Opened 2021-09-14 06:54 UTC by ndijkstra

2021-09-17 12:46 UTC, Timollie requested changes

2021-09-17 12:46 UTC, Timollie commented on source/reference/v2/payments-api/create-payment.rst
> +   contain symbols.
Can you define symbols here? I assume you meant special characters like "%$#@&*(" etc.
Does it always need to contain a number?

2021-09-17 12:46 UTC, Timollie commented on source/reference/v2/payments-api/create-payment.rst
> +   If a description in the form ``Order <order number>`` is used and the <order number> is right after the ``Order``
Suggestion: Change to <order number> to <orderNumber>. Also might be nice to add that only the next value, separation by whitespaces, after "Order" is picked up.

2021-09-23 08:03 UTC, ndijkstra commented on source/reference/v2/payments-api/create-payment.rst
> +   contain symbols.
I think "symbols" is well known in the developer world so no need to specify all the symbols.

2021-09-23 08:06 UTC, ndijkstra commented on source/reference/v2/payments-api/create-payment.rst
> +   If a description in the form ``Order <order number>`` is used and the <order number> is right after the ``Order``
Do you have a suggestion for the whole sentence?

2021-09-23 10:11 UTC, Timollie commented on source/reference/v2/payments-api/create-payment.rst
> +   If a description in the form ``Order <order number>`` is used and the <order number> is right after the ``Order``
Suggestion => If a description like ``Order <orderNumber>`` is used and the first value after ``Order``, separates by whitespaces, contains at least some numbers, it will be passed to PayPal as the *invoice reference*.

Not sure on "value", maybe use "entry" or "word". I do not know the right technical term for part of a string.

Edit example:
- Order Best Service ABS123 does not match as the first value after "Order", "Best", does not contain any numbers.

Then add example:
- Order ABS123 Best Service, will match and thus the first value after Order ``Order ABS123`` will be sent to PayPal

2021-09-23 10:12 UTC, Timollie requested changes
See comment: https://github.com/mollie/api-documentation/pull/805/files#r714653907

2021-09-23 10:59 UTC, Timollie approved these changes

2021-09-23 10:59 UTC, merged