FSP-729 - Balances public APIs docs
mollie/api-documentation pull request #847
Opened 2022-05-02 10:26 UTC by martinmikan

[FSP-729](https://mollie.atlassian.net/browse/FSP-729)

2022-05-02 10:53 UTC, mollierobbert requested changes

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +   :url: https://api.mollie.com/v2/balances/*apiBalanceToken*
`*balanceId*` follows the convention. We only call them 'API token' internally.

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +Replace ``apiBalanceToken`` in the endpoint URL by the balance token, which can be retrieved by the
Replace ``balanceId`` in the endpoint URL by the balance ID...

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +       example ``bal_8irzh1y2``.
Is it too late to introduce UUID-based tokens for balances, now that we still can?

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +              balance amount is to be transferred to.
NBC: lines can be up to 120 chars wide. These two lines probably fit on one line.

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +            - Prefix token of the bank account.
"ID of the bank account."

Will this be the first time we expose bank account IDs in our public API? Again, we should consider introducing UUIDs.

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +            - Prefix token of the bank account.
Maybe we should leave the parameter out altogether, since we don't have a Bank Accounts API yet anyway. We can always add it later.

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/get-primary-balance.rst
> +
I think the copy here should explain how this is just an alias. Something like:

"Retrieve the primary balance. This is the balance of your account's primary currency, where all payments are settled to by default.

This endpoint is an alias of the <Get balance endpoint>. Please refer to the documentation of that endpoint for more information."

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/get-primary-balance.rst
> +
So then all the below paragraphs can go, since it duplicates the other page.

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/get-primary-balance.rst
> +.. list-table::
We don't need to duplicate all of this, since it's just an alias endpoint.

See for example:
https://docs.mollie.com/reference/v2/organizations-api/current-organization
vs.:
https://docs.mollie.com/reference/v2/organizations-api/get-organization

The request is left out entirely on the first one, and it just points to the second one.

2022-05-02 10:53 UTC, mollierobbert commented on source/reference/v2/balances-api/list-balances.rst
> +Retrieve all the organization's balances, including the default balance, ordered from newest to oldest.
...including the primary balance...

2022-05-02 10:53 UTC, mollierobbert commented on source/theme/sidebar-reference-v2.html
> +  </li>
There is also a big `if` switch in `layout.html`. Can you add the Balances API there as well, if it's not there yet?

2022-05-04 11:43 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +===================
```suggestion
===========
```

2022-05-04 11:45 UTC, mollierobbert approved these changes

2022-05-04 13:14 UTC, robindirksen1 commented
@martinmikan maybe this is out of the scope, but is it possible to view/list all `transactions` on a specific balance with the public API?

2022-11-15 08:50 UTC, mollierobbert commented
Already merged in a different PR.

2022-11-15 08:50 UTC, closed without merging