Update orderlines endpoint
mollie/api-documentation pull request #857
Opened 2022-06-13 12:55 UTC by maicolgarces

2022-06-13 14:04 UTC, sandervanhooft commented on source/reference/v2/orders-api/overview.rst
> +   Update, add or cancel multiple order lines of a specific order line.
I think that last "line" should go.

2022-06-15 11:13 UTC, maicolgarces commented on source/reference/v2/orders-api/update-order-lines.rst
> +.. parameter:: update-payload
This i something I am not sure how to represent. As we have an array of multiple object types we need a way to represent each one of them. With this approach it would appear like this:

![Screenshot 2022-06-15 at 13 11 59](https://user-images.githubusercontent.com/73994248/173813861-61de8bce-d512-4f92-8b3b-30fb418d60dc.png)

Another idea I had was to have multiple `operation` fields, but describing them as add, update, or cancel separately.

2022-06-15 12:02 UTC, zoltanczirkos-mollie approved these changes

2022-06-21 13:22 UTC, jennifer-hemmens requested changes
Reviewed the descriptions, feel free to throw questions at me or disagree where I've misinterpreted something.

**General notes:**

- Consider renaming this to "Manage order lines" or let's come up with a better word than "Update", because it's not the only thing you can do with this endpoint
- Check the data objects to make sure the params are all in the same order for consistency

2022-06-21 13:22 UTC, jennifer-hemmens commented on source/reference/v2/orders-api/update-order-lines.rst
> +         Must be less than the number of items already shipped or canceled for this order line.
The number of items in the order line that you want to cancel. This should be lower than or equal to the number of remaining items in a (partially shipped) order line.

If the `quantity` is not specified in the request, the entire order line is canceled. For partially shipped order lines, all remaining items are canceled.

2022-06-21 13:22 UTC, jennifer-hemmens commented on source/reference/v2/orders-api/update-order-lines.rst
> +         ``extra.maximumAmount`` properties that allow you pick the right amount.
The amount that you want to cancel. In almost all cases, Mollie calculates the amount automatically.

This field is only required when partially canceling an order line that has a ``discountAmount`` greater than 0.

The maximum amount you can cancel is ``unit price  x quantity to cancel``.

The minimum amount depends on the discount applied to the order line, the quantity of items already shipped or canceled, the amounts already shipped or canceled, and the quantity that you want to cancel.

If the `amount` is not specified in the request, Mollie automatically calculates the amount. In case it can't calculate the amount automatically, Mollie returns an error that contains the ``extra.minimumAmount`` and ``extra.maximumAmount`` properties, enabling you to choose the applicable amount.

2022-06-21 13:22 UTC, jennifer-hemmens commented on source/reference/v2/orders-api/update-order-lines.rst
> +:doc:`OAuth app </connect/overview>`, you can enable test mode through the ``testmode`` parameter.
To use :doc:`organization access tokens </overview/authentication>` or to create an :doc:`OAuth app </connect/overview>`, enable test mode using the ``testmode`` parameter.

2022-06-21 13:22 UTC, jennifer-hemmens commented on source/reference/v2/orders-api/update-order-lines.rst
> +   Set this to ``true`` to update a test mode order line.
Set ``testmode`` to ``true`` to update an order line that was created in test mode.

2022-06-21 13:22 UTC, jennifer-hemmens commented on source/reference/v2/orders-api/update-order-lines.rst
> +An order object is returned, as described in
Returns an :doc:`order object </reference/v2/orders-api/get-order>`.

2022-06-21 13:22 UTC, jennifer-hemmens commented on source/theme/sidebar-reference-v2.html
> +        'Update order lines'
Maybe a more generic word, such as "Manage order lines" makes more sense as a title? Considering this endpoint allows you to update, add, or cancel order lines, not just update :)

2022-06-22 09:25 UTC, jennifer-hemmens commented on source/reference/v2/orders-api/manage-order-lines.rst
> +   When updating order lines for orders that used a pay after delivery method such as Klarna Pay Later, the supplier (Klarna) may decline the requested changes. This results in an error response from
The initial order

2022-06-22 09:30 UTC, jennifer-hemmens commented on source/reference/v2/orders-api/manage-order-lines.rst
> +To use :doc:organization access tokens </overview/authentication> or to create an :doc:OAuth app </connect/overview>, enable test mode using the testmode parameter.
Maybe "enable test mode using the ``testmode`` parameter."

2022-06-22 09:41 UTC, jennifer-hemmens approved these changes

2022-07-04 10:29 UTC, mollierobbert approved these changes

2022-07-04 10:29 UTC, mollierobbert commented on source/changelog/v2/changelog.rst
> +=============
NBC: can you fix the underline length for all three cases (`June 2022`, `Friday, 24th`, `Monday, 20th`)? They should align with the title.

2022-07-04 10:29 UTC, mollierobbert commented on source/reference/v2/orders-api/manage-order-lines.rst
> +Use this endpoint to update, cancel, or add one or more order lines. This endpoint sends a single authorisation request that contains the final order lines and amount to the supplier.
NBC: can you adjust the whole document to the 120 character line length? Makes it easier to read the file in the IDE.

2022-07-04 10:29 UTC, mollierobbert commented on source/reference/v2/orders-api/manage-order-lines.rst
> +   When updating order lines for orders that used a pay after delivery method such as Klarna Pay Later, the supplier (Klarna) may decline the requested changes. This results in an error response from
This should be a webhook ultimately, right? I guess it's fine for now.

2022-07-04 10:29 UTC, mollierobbert commented on source/reference/v2/orders-api/manage-order-lines.rst
> +                        "operation": "update"
NBC: maybe move `"operation"` above `"data"` in the examples. I think that's easier to understand/read.

2022-07-04 10:29 UTC, mollierobbert commented on source/theme/sidebar-reference-v2.html
> +        'Manage order lines'
Maybe 'change order lines' instead of 'manage'? CC @jennifer-hemmens

2022-11-21 22:28 UTC, mollierobbert commented on source/reference/v2/orders-api/manage-order-lines.rst
> +   (Klarna) may decline the requested changes. This results in an error response from the Mollie API. The order initial remains intact without applying the requested changes.
Don't we want a webhook here instead?

2022-11-22 10:53 UTC, maicolgarces commented on source/reference/v2/orders-api/manage-order-lines.rst
> +   (Klarna) may decline the requested changes. This results in an error response from the Mollie API. The order initial remains intact without applying the requested changes.
This call is synchronous, so we will receive the response from the supplier as part of call to the API, so no need for a webhook.

2022-12-20 14:20 UTC, sandervanhooft commented on source/reference/v2/orders-api/manage-order-lines.rst
> +      curl -X PATCH https://api.mollie.com/v2/orders/ord_pbjz8x/lines/odl_dgtxyl \
Shouldn't this url be `https://api.mollie.com/v2/orders/ord_pbjz8x/lines` instead?

2022-12-20 14:38 UTC, sandervanhooft commented on source/reference/v2/orders-api/manage-order-lines.rst
> +    "id": "ord_xvb27g",
id doesn't match example request url

2023-02-15 11:08 UTC, merged