Balance API public docs
mollie/api-documentation pull request #882
Opened 2022-10-27 09:29 UTC by serhiidaletskyi

Refined continuation of https://github.com/mollie/api-documentation/pull/847

2022-10-27 10:35 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +    The frequency at which the available amount on the balance will be transferred away to the configured transfer
Maybe replace `transferred away` with `settled`, since we tend to use 'settlement' as the standard term for getting paid out to your bank account.

2022-10-27 10:36 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +    .. note:: If the transfer is for an external destination, and the transfer is created in a weekend or during a
We currently only support external transfers, so let's change this note to:

```
note: Settlements created during weekends or on bank holidays will take place on the next business day.
```

2022-10-27 10:48 UTC, mollierobbert commented on source/reference/v2/balances-api/list-balance-transactions.rst
> +
Double newline.

2022-10-27 11:17 UTC, mollierobbert commented on source/reference/v2/balances-api/overview.rst
> +mutation (aggregates) per balance in a certain timeframe. All data is available from July 1st 2022.
These three paragraphs need to be rewritten a bit, I think.

It's a bit confusing currently, and it uses the Dutchism 'mutations' which is not actual English.

I suggest we use the following copy:

> The Balances API allows you to retrieve real-time as well as historical information about your Mollie balance. This may be useful for example to integrate Mollie deeper into your bookkeeping, or for white label solutions to enrich the experience they offer their Mollie users.
> 
> With the Balances API, you can:
> * Retrieve your real-time open balance
> * Retrieve the balance movements that took place on your balance (e.g. payments, refunds, etc.)
> * Retrieve aggregated time-based reports of those balance movements
> 
> The Balances API has some overlap with the :doc:'Settlements API'<link>. The Settlements API allows you to retrieve the fixed list of balance movements that were included in each settlement. The Balances API allows you to retrieve the real-time stream of balance movements, and to build aggregated reports. Both APIs can be used for accounting and reconciliation purposes.
> 
> .. note: Due to technical limitations, data from before 1 July 2022 is not available via this API.

2022-10-27 11:23 UTC, mollierobbert commented on source/reference/v2/balances-api/overview.rst
> +   <span class="api-name__beta">BETA</span>
Can you turn this into a Sphinx directive? See for example `ApiEndpointDirective`. It can simply be a directive that only outputs this snippet of HTML, all fine. And then we can style it appropriately component-based instead of having a page-specific `balance-api.scss` file.

2022-10-27 11:23 UTC, mollierobbert requested changes
See comments.

2022-10-27 14:29 UTC, serhiidaletskyi commented on source/reference/v2/balances-api/get-balance.rst
> +With the Balances API you can retrieve your current balance. The response includes three amounts:
Yes, fixed.

2022-10-27 14:30 UTC, serhiidaletskyi commented on source/reference/v2/balances-api/get-balance.rst
> +    .. note:: If the transfer is for an external destination, and the transfer is created in a weekend or during a
Done.

2022-10-27 14:30 UTC, serhiidaletskyi commented on source/reference/v2/balances-api/list-balance-transactions.rst
> +
Fixed.

2022-10-27 14:31 UTC, serhiidaletskyi commented on source/reference/v2/balances-api/overview.rst
> +Balance API
We discussed it with Julien M. before and agreed to leave it in singular.

2022-10-27 14:32 UTC, serhiidaletskyi commented on source/reference/v2/balances-api/overview.rst
> +mutation (aggregates) per balance in a certain timeframe. All data is available from July 1st 2022.
Thanks for the suggestion, Julien tweaked it a bit and I changed.

2022-10-27 14:42 UTC, serhiidaletskyi commented
> See comments.

@mollierobbert Made changes as per your suggestions.

2022-10-27 14:43 UTC, mollierobbert commented on source/changelog/v2/changelog.rst
> +- Added new ``Balance API`` docs.
Balances API, plural

2022-10-27 14:43 UTC, mollierobbert commented on source/reference/v2/balances-api/get-balance.rst
> +    The transfer reference set to be included in all the transfer for this balance. Either a string or ``null``.
'all the transfer**s**', plural

2022-10-27 14:47 UTC, mollierobbert commented on source/reference/v2/balances-api/overview.rst
> +Balance API
It really has to be plural. In the body text as well. All our APIs have plural names.

2022-10-27 14:47 UTC, mollierobbert commented on source/reference/v2/balances-api/overview.rst
> +   <span class="api-name__beta">BETA</span>
OK, ship it like this, I'll fix it later.

2022-10-27 14:48 UTC, mollierobbert commented on source/reference/v2/balances-api/overview.rst
> +Balance API
I disagree, I think it has to be plural. All our APIs have plural names. For example Organizations API is plural, despite most users only having one organization.

2022-10-27 14:52 UTC, mollierobbert commented on source/reference/v2/balances-api/overview.rst
> +The Balance API has some overlap with the :doc:'Settlements API', since the Settlements API allows you to retrieve the fixed list of balance movements that were included in each settlement.
Sorry, you copy-pasted literally 😅. The link should be like this:

```
:doc:`Settlements API </reference/v2/settlements-api/overview>`
```

2022-10-28 06:47 UTC, serhiidaletskyi commented on source/changelog/v2/changelog.rst
> +- Added new ``Balance API`` docs.
Changed.

2022-10-28 06:47 UTC, serhiidaletskyi commented on source/reference/v2/balances-api/get-balance.rst
> +    The transfer reference set to be included in all the transfer for this balance. Either a string or ``null``.
Done.

2022-10-28 06:48 UTC, serhiidaletskyi commented on source/reference/v2/balances-api/overview.rst
> +The Balance API has some overlap with the :doc:'Settlements API', since the Settlements API allows you to retrieve the fixed list of balance movements that were included in each settlement.
Yes, my bad 😄 Fixed the link.

2022-10-28 07:25 UTC, mollierobbert approved these changes

2022-10-28 07:26 UTC, merged