More specific QR documentation + wait for webhook on payment
mollie/api-documentation pull request #888
Opened 2022-11-15 08:48 UTC by arnetm

2022-11-15 08:51 UTC, mollierobbert commented on source/payments/qr-codes.rst
> +At Mollie, we support 2 types of payment QR codes: The payment specific QR-codes and the payment link QR codes.
`2` -> `two`

`payment specific QR-codes` -> `payment-specific QR codes`

2022-11-15 08:52 UTC, mollierobbert commented on source/payments/qr-codes.rst
> +#. A payment method specific QR code is created by Mollie and is following the same expiry pattern like the :doc:`basic payment flow </payments/accepting-payments#the-basic-payment-flow>`.
`and is following` -> `and follows`
`like` -> `as`

2022-11-15 08:52 UTC, mollierobbert commented on source/payments/qr-codes.rst
> +   supported methods and how a consumer should use the QR-code.
`QR-code` -> `QR code`

2022-11-15 08:54 UTC, mollierobbert commented on source/payments/qr-codes.rst
> +   This QR code expires at the same time the created payment expires. This can be created via the :doc:`payments API </reference/v2/payments-api/overview>` or
`This QR code expires at the same time the created payment expires`
-> `When a payment with a QR code expires, the QR code itself expires as well`

2022-11-15 08:54 UTC, mollierobbert commented on source/payments/qr-codes.rst
> +   This QR code expires at the same time the created payment expires. This can be created via the :doc:`payments API </reference/v2/payments-api/overview>` or
`This can be created via the`
-> `This type of QR code can be created via the`

2022-11-15 08:55 UTC, mollierobbert commented on source/payments/qr-codes.rst
> +   The advice though here is to only use mobile friendly methods, such as Paypal, Bancontact and Ideal. This can be created by creating a payment link via the :doc:`payment link API <//reference/v2/p
`The advice though here is to only use mobile friendly methods, such as Paypal, Bancontact and Ideal.`
-> `We advise to only use mobile-friendly methods, such as PayPal, Bancontact, and iDEAL.`

2022-11-15 08:55 UTC, mollierobbert commented on source/payments/qr-codes.rst
> +   The advice though here is to only use mobile friendly methods, such as Paypal, Bancontact and Ideal. This can be created by creating a payment link via the :doc:`payment link API <//reference/v2/p
`This can be created by creating a payment link`
-> `This type of QR code can be created by creating a payment link`

2022-11-15 08:56 UTC, mollierobbert commented on source/payments/qr-codes.rst
> +   and converting this ``paymentLink`` URL to a QR code via a link to QR code tool/SDK. The expiry time of the QR-code can be defined via the ``expiresAt`` parameter.
`...URL to a QR code via a link to QR code tool/SDK`
-> `...URL to a QR code via most common QR code tools available for most programming languages`

2022-11-15 08:58 UTC, mollierobbert requested changes
See comments

2022-11-15 20:08 UTC, willemstuursma commented on source/payments/qr-codes.rst
> +   This QR code expires at the same time the created payment expires. This can be created via the :doc:`payments API </reference/v2/payments-api/overview>` or
It might be nice to remark that the payment specific QR codes can often be scanned with method specific apps, such as the Bancontact or iDEAL app.

2022-11-17 09:40 UTC, mollierobbert commented
Cheers!

2022-11-17 09:43 UTC, mollierobbert commented
The pipeline is still failing @arnetm:

```
/home/travis/build/mollie/api-documentation/source/payments/qr-codes.rst:14:unknown document: /payments/accepting-payments#the-basic-payment-flow
```

You need to label the heading in order to link to that specific heading due to Sphinx limitations. I think the easiest way is to just remove the `#the-basic-payment-flow` part for now.

2022-11-17 10:56 UTC, arnetm commented
Tried editing the title - didn't work. Will remove it in full.

2022-12-12 12:41 UTC, mollierobbert approved these changes

2022-12-12 12:41 UTC, merged