Refresh Application Fee documentation
mollie/api-documentation pull request #950
Opened 2023-06-22 12:55 UTC by pgoodjohn

2023-07-07 10:13 UTC, mollierobbert commented on source/connect/application-fees.rst
> +refunds and chargebacks. If you want to split a payment with another party (for instance if you are a marketplace),
I'd use commas here. Parentheses are not commonly used for sub-sentences in English.

> ...with another party, for instance if you run a marketplace, we offer...

2023-07-07 10:14 UTC, mollierobbert commented on source/connect/application-fees.rst
> +      A ticketing platform wants to charge a fee per successful payment to each connected theatre. In this case, each theatre has an account
We use American English, so 'theater'.

2023-07-07 10:15 UTC, mollierobbert commented on source/connect/application-fees.rst
> +      fee is automatically transferred from the theatre’s account to the platforms account.
> ...to the platform's account.

2023-07-07 10:17 UTC, mollierobbert commented on source/connect/application-fees.rst
> +Max application fee = amount of the payment - 1.21 × (0.29 + (0.05 × the amount of the payment))
Can we not simplify this by now? It's annoying to deal with this unpredictable maximum, and it's inconsistent with the Orders API.

2023-07-07 10:27 UTC, mollierobbert commented on source/connect/application-fees.rst
> +Any application fee has a maximum as sufficient funds need to be available to pay the payment fee.
How about:

> Since Mollie usually also charges a fee on every payment, there is a limit to the maximum application fee amount.
>
> The Mollie fee charged will depend on which method the consumer selects. To keep things simple however, we reserve €0,29 + 5% of the payment amount for us to be able to charge the Mollie fee, multiplied by 21% to cover Dutch VAT.
>
> This means the maximum can be calculated as follows:

2023-07-07 10:31 UTC, mollierobbert commented on source/connect/application-fees.rst
> +You can submit the `applicationFee` parameter in test mode. The application fee will be visible in the payment details
Single backtick makes it cursive I believe. Double backticks all the way.

2023-07-07 10:32 UTC, mollierobbert requested changes
See comments.

2023-07-07 11:09 UTC, pgoodjohn commented on source/connect/application-fees.rst
> +Max application fee = amount of the payment - 1.21 × (0.29 + (0.05 × the amount of the payment))
It is not unpredictable though, the formula is always the same with the payment amount you can reliably calculate what the maximum will be. 

For now I would keep these docs as they are to be as transparent as possible, with the extended description we added I feel like it is easier to understand what's going on in the formula.

For the orders limit, I would like to unify or completely remove these maxima, but that's something that I'd prefer to approach with more thought rather than just yoloing it while changing some docs 😛

2023-07-10 09:17 UTC, mollierobbert commented on source/connect/application-fees.rst
> +Max application fee = amount of the payment - 0.35 + (0.06 × the amount of the payment)
I believe you rounded to €0,36 in code.

2023-07-10 09:42 UTC, mollierobbert approved these changes

2023-07-10 09:42 UTC, merged